as yet unclassified
loadGrey
	<loadColor>
	self
		atColor: #grey add: 50 -> 'fafafa';
		atColor: #grey add: 100 -> 'f5f5f5';
		atColor: #grey add: 200 -> 'eeeeee';
		atColor: #grey add: 300 -> 'e0e0e0';
		atColor: #grey add: 400 -> 'bdbdbd';
		atColor: #grey add: 500 -> '9e9e9e';
		atColor: #grey add: 600 -> '757575';
		atColor: #grey add: 700 -> '616161';
		atColor: #grey add: 800 -> '424242';
		atColor: #grey add: 900 -> '212121'