as yet unclassified
loadPurple
	<loadColor>
	self
		atColor: #purple add: 50 -> 'f3e5f5';
		atColor: #purple add: 100 -> 'e1bee7';
		atColor: #purple add: 200 -> 'ce93d8';
		atColor: #purple add: 300 -> 'ba68c8';
		atColor: #purple add: 400 -> 'ab47bc';
		atColor: #purple add: 500 -> '9c27b0';
		atColor: #purple add: 600 -> '8e24aa';
		atColor: #purple add: 700 -> '7b1fa2';
		atColor: #purple add: 800 -> '6a1b9a';
		atColor: #purple add: 900 -> '4a148c'