as yet unclassified
loadPink
	<loadColor>
	self
		atColor: #pink add: 50 -> 'fce4ec';
		atColor: #pink add: 100 -> 'f8bbd0';
		atColor: #pink add: 200 -> 'f48fb1';
		atColor: #pink add: 300 -> 'f06292';
		atColor: #pink add: 400 -> 'ec407a';
		atColor: #pink add: 500 -> 'e91e63';
		atColor: #pink add: 600 -> 'd81b60';
		atColor: #pink add: 700 -> 'c2185b';
		atColor: #pink add: 800 -> 'ad1457';
		atColor: #pink add: 900 -> '880e4f'