Class {
	#name : #BlDevScripterMultipleCheckStep,
	#superclass : #BlDevScripterCompositeStep,
	#traits : 'TBlDevScripterCheckStep - {#addStep:}',
	#classTraits : 'TBlDevScripterCheckStep classTrait',
	#category : #'Bloc-DevTool-Scripter-Steps'
}

{ #category : #accessing }
BlDevScripterMultipleCheckStep >> defaultLabel [
	^ 'Checks'
]

{ #category : #initialization }
BlDevScripterMultipleCheckStep >> initialize [
	super initialize.

	
]
