SystemOrganization addCategory: #Bloc!
SystemOrganization addCategory: 'Bloc-Basic'!
SystemOrganization addCategory: 'Bloc-Basic-Changes'!
SystemOrganization addCategory: 'Bloc-Basic-Properties'!
SystemOrganization addCategory: 'Bloc-Basic-Support'!
SystemOrganization addCategory: 'Bloc-Basic-Transformations'!
SystemOrganization addCategory: 'Bloc-Basic-Visual'!
SystemOrganization addCategory: 'Bloc-Effect'!
SystemOrganization addCategory: 'Bloc-Event'!
SystemOrganization addCategory: 'Bloc-EventHandling'!
SystemOrganization addCategory: 'Bloc-Gesture'!
SystemOrganization addCategory: 'Bloc-KeyBinding'!
SystemOrganization addCategory: 'Bloc-Layouts-Basic'!
SystemOrganization addCategory: 'Bloc-Layouts-Support'!
SystemOrganization addCategory: 'Bloc-Paint'!
SystemOrganization addCategory: 'Bloc-Paint-Support'!
SystemOrganization addCategory: 'Bloc-Property'!
SystemOrganization addCategory: 'Bloc-Settings'!
SystemOrganization addCategory: 'Bloc-Space'!
SystemOrganization addCategory: 'Bloc-Space-Support'!
SystemOrganization addCategory: 'Bloc-State'!
SystemOrganization addCategory: 'Bloc-Universe'!
SystemOrganization addCategory: 'Bloc-Utilities - Debugging'!
SystemOrganization addCategory: 'Bloc-Utilities - Drag&Drop'!
SystemOrganization addCategory: 'Bloc-Utilities - Focus'!
SystemOrganization addCategory: 'Bloc-Utilities - Scalable'!
SystemOrganization addCategory: 'Bloc-Utilities - Selection'!
