Class {
	#name : #BlCompositionRasterizer,
	#superclass : #Object,
	#instVars : [
		'canvas'
	],
	#category : #'Bloc-Compositor-Layers'
}

{ #category : #accessing }
BlCompositionRasterizer >> canvas [
	^ canvas
]

{ #category : #accessing }
BlCompositionRasterizer >> canvas: anObject [
	canvas := anObject
]

{ #category : #'as yet unclassified' }
BlCompositionRasterizer >> rasterize: aCompositionLayer [
	
]
