Class {
	#name : #BlTextNullStyler,
	#superclass : #BlTextStyler,
	#category : #'Bloc-Text-Text-Styler'
}

{ #category : #private }
BlTextNullStyler >> privateStyle: aText [
]

{ #category : #private }
BlTextNullStyler >> style: aBrText [
]

{ #category : #private }
BlTextNullStyler >> styleInBackgroundProcess: aBrText [
]

{ #category : #styling }
BlTextNullStyler >> styleInBackgroundProcess: aBrText andAfterDo: aBlock [
]
