"
# Dashed style
{{gtExample:BlTextDecorationStyleExamples>>#dashed|codeExpanded=false|previewExpanded=true|previewShow=#gtPreviewFor:|previewHeight=50}}

"
Class {
	#name : 'BlTextDecorationDashedStyle',
	#superclass : 'BlTextDecorationStyle',
	#package : 'Bloc',
	#tag : 'Text-Text-Decoration',
	#package : 'Bloc-Text',
	#tag : 'Text-Decoration'
}

{ #category : 'accessing' }
BlTextDecorationDashedStyle class >> constructor [
	^ #dashed
]

{ #category : 'accessing' }
BlTextDecorationDashedStyle class >> label [
	^ 'Dashed'
]
