"
# Double style
{{gtExample:BlTextDecorationStyleExamples>>#double|codeExpanded=false|previewExpanded=true|previewShow=#gtPreviewFor:|previewHeight=50}}

"
Class {
	#name : #BlTextDecorationDoubleStyle,
	#superclass : #BlTextDecorationStyle,
	#category : 'Bloc-Text-Text-Decoration'
}

{ #category : #accessing }
BlTextDecorationDoubleStyle class >> constructor [
	^ #double
]

{ #category : #accessing }
BlTextDecorationDoubleStyle class >> label [
	^ 'Double'
]
