Class {
	#name : #BlDemoData2,
	#superclass : #Object,
	#category : #'Bloc-Demo-NodeTests'
}

{ #category : #'as yet unclassified' }
BlDemoData2 >> returnBlElement [

	<sampleInstance>
	^ BlElement new background: Color blue
]

{ #category : #'as yet unclassified' }
BlDemoData2 >> returnBlElement2 [

	<sampleInstance>
	^ BlElement new background: Color red
]

{ #category : #'as yet unclassified' }
BlDemoData2 >> returnBlElement3 [

	<sampleInstance>
	^ BlElement new background: Color blue
]

{ #category : #'as yet unclassified' }
BlDemoData2 >> returnBlElement4 [

	<sampleInstance>
	^ nil
]
