"
Is sent by the space after is it detached from the universe.
"
Class {
	#name : 'BlSpaceDetachedEvent',
	#superclass : 'BlSpaceEvent',
	#instVars : [
		'space'
	],
	#category : 'Bloc-Events-Type-Space',
	#package : 'Bloc',
	#tag : 'Events-Type-Space'
}

{ #category : 'accessing' }
BlSpaceDetachedEvent >> space [
	^ space
]

{ #category : 'accessing' }
BlSpaceDetachedEvent >> space: anObject [
	space := anObject
]
