"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : 'ManifestBlocHostOSWindow',
	#superclass : 'PackageManifest',
	#category : 'BlocHost-OSWindow',
	#package : 'BlocHost-OSWindow'
}

{ #category : 'code-critics' }
ManifestBlocHostOSWindow class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'BlocHost-OSWindow')) #'2017-06-14T17:38:49.744375+02:00') )
]
